"""Add ticket model for SAV workflow

Revision ID: 610ffe6e81fe
Revises: 001_initial
Create Date: 2026-01-04 15:02:30.820878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610ffe6e81fe'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('leads_createdAt_idx'), table_name='leads')
    op.drop_index(op.f('leads_email_idx'), table_name='leads')
    op.drop_index(op.f('leads_status_idx'), table_name='leads')
    op.drop_index(op.f('leads_userId_idx'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('_prisma_migrations')
    op.drop_index(op.f('ix_sav_tickets_created_at'), table_name='sav_tickets')
    op.drop_index(op.f('ix_sav_tickets_customer_id'), table_name='sav_tickets')
    op.drop_index(op.f('ix_sav_tickets_order_number'), table_name='sav_tickets')
    op.drop_index(op.f('ix_sav_tickets_priority'), table_name='sav_tickets')
    op.drop_index(op.f('ix_sav_tickets_status'), table_name='sav_tickets')
    op.drop_index(op.f('ix_sav_tickets_ticket_id'), table_name='sav_tickets')
    op.drop_table('sav_tickets')
    op.drop_index(op.f('messages_conversationId_idx'), table_name='messages')
    op.drop_index(op.f('messages_role_idx'), table_name='messages')
    op.drop_index(op.f('messages_timestamp_idx'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('conversations_sessionId_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_startedAt_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_status_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_userId_idx'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('feedback_createdAt_idx'), table_name='feedback')
    op.drop_index(op.f('feedback_rating_idx'), table_name='feedback')
    op.drop_index(op.f('feedback_sessionId_idx'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('analytics_events_eventType_idx'), table_name='analytics_events')
    op.drop_index(op.f('analytics_events_sessionId_idx'), table_name='analytics_events')
    op.drop_index(op.f('analytics_events_timestamp_idx'), table_name='analytics_events')
    op.drop_index(op.f('analytics_events_userId_idx'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('product_recommendations_clicked_idx'), table_name='product_recommendations')
    op.drop_index(op.f('product_recommendations_messageId_idx'), table_name='product_recommendations')
    op.drop_index(op.f('product_recommendations_productId_idx'), table_name='product_recommendations')
    op.drop_index(op.f('product_recommendations_purchased_idx'), table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('system_metrics_metricName_idx'), table_name='system_metrics')
    op.drop_index(op.f('system_metrics_metricType_idx'), table_name='system_metrics')
    op.drop_index(op.f('system_metrics_timestamp_idx'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'ADMIN', 'API_SERVICE', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_index(op.f('users_createdAt_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_index(op.f('users_email_key'), table_name='users')
    op.drop_index(op.f('users_sessionId_idx'), table_name='users')
    op.drop_index(op.f('users_sessionId_key'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('users', 'concerns')
    op.drop_column('users', 'hairType')
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'sessionId')
    op.drop_column('users', 'lastSeenAt')
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.TEXT(), server_default=sa.text("'ar'::text"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('sessionId', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hairType', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('concerns', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('users_sessionId_key'), 'users', ['sessionId'], unique=True)
    op.create_index(op.f('users_sessionId_idx'), 'users', ['sessionId'], unique=False)
    op.create_index(op.f('users_email_key'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=False)
    op.create_index(op.f('users_createdAt_idx'), 'users', ['createdAt'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'api_key_hash')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    op.create_table('system_metrics',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metricType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metricName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statusCode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('errorType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_metrics_pkey'))
    )
    op.create_index(op.f('system_metrics_timestamp_idx'), 'system_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('system_metrics_metricType_idx'), 'system_metrics', ['metricType'], unique=False)
    op.create_index(op.f('system_metrics_metricName_idx'), 'system_metrics', ['metricName'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('messageId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('productId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('productName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clicked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('purchased', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['messageId'], ['messages.id'], name=op.f('product_recommendations_messageId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_recommendations_pkey'))
    )
    op.create_index(op.f('product_recommendations_purchased_idx'), 'product_recommendations', ['purchased'], unique=False)
    op.create_index(op.f('product_recommendations_productId_idx'), 'product_recommendations', ['productId'], unique=False)
    op.create_index(op.f('product_recommendations_messageId_idx'), 'product_recommendations', ['messageId'], unique=False)
    op.create_index(op.f('product_recommendations_clicked_idx'), 'product_recommendations', ['clicked'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sessionId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eventType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('eventName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('analytics_events_userId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_pkey'))
    )
    op.create_index(op.f('analytics_events_userId_idx'), 'analytics_events', ['userId'], unique=False)
    op.create_index(op.f('analytics_events_timestamp_idx'), 'analytics_events', ['timestamp'], unique=False)
    op.create_index(op.f('analytics_events_sessionId_idx'), 'analytics_events', ['sessionId'], unique=False)
    op.create_index(op.f('analytics_events_eventType_idx'), 'analytics_events', ['eventType'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sessionId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('feedback_sessionId_idx'), 'feedback', ['sessionId'], unique=False)
    op.create_index(op.f('feedback_rating_idx'), 'feedback', ['rating'], unique=False)
    op.create_index(op.f('feedback_createdAt_idx'), 'feedback', ['createdAt'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sessionId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.TEXT(), server_default=sa.text("'ar'::text"), autoincrement=False, nullable=False),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('endedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('messageCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('hairType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('concerns', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='conversations_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('conversations_userId_idx'), 'conversations', ['userId'], unique=False)
    op.create_index(op.f('conversations_status_idx'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('conversations_startedAt_idx'), 'conversations', ['startedAt'], unique=False)
    op.create_index(op.f('conversations_sessionId_idx'), 'conversations', ['sessionId'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tokensUsed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responseTime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], name=op.f('messages_conversationId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('messages_timestamp_idx'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('messages_role_idx'), 'messages', ['role'], unique=False)
    op.create_index(op.f('messages_conversationId_idx'), 'messages', ['conversationId'], unique=False)
    op.create_table('sav_tickets',
    sa.Column('ticket_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('product_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('problem_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problem_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('problem_severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('problem_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('warranty_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('warranty_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priority_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('auto_resolved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resolution_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resolution_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tone_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tone_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tone_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sla_response_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sla_intervention_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('client_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('sav_tickets_pkey'))
    )
    op.create_index(op.f('ix_sav_tickets_ticket_id'), 'sav_tickets', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_sav_tickets_status'), 'sav_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_sav_tickets_priority'), 'sav_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_sav_tickets_order_number'), 'sav_tickets', ['order_number'], unique=False)
    op.create_index(op.f('ix_sav_tickets_customer_id'), 'sav_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sav_tickets_created_at'), 'sav_tickets', ['created_at'], unique=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('leads',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=False),
    sa.Column('interest', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('budget', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timeline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('leads_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    op.create_index(op.f('leads_userId_idx'), 'leads', ['userId'], unique=False)
    op.create_index(op.f('leads_status_idx'), 'leads', ['status'], unique=False)
    op.create_index(op.f('leads_email_idx'), 'leads', ['email'], unique=False)
    op.create_index(op.f('leads_createdAt_idx'), 'leads', ['createdAt'], unique=False)
    # ### end Alembic commands ###
